version: '3'
volumes:
  data:
networks:
  db_network:
  web_network:
  queue_network:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      # Volume data
      - data:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network
  frontend:
    image: nginx:1.13
    volumes:
      # Website
      - ./web:/usr/share/nginx/html/
      # Reverse proxy
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web_network
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      # App
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - db_network
      - web_network
      - queue_network
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=old_database #Override in docker-compose.override.yml
  queue:
    image: redis:3.2
    networks:
      - queue_network
  worker:
    build: worker
    volumes:
      # Worker
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - queue_network
    depends_on:
      - queue